### ISSUE TITLE
Does not build (XslTransformation)

### ISSUE THREAD

**Issue by panicbit** [zivillian/ldap.net#10]
When trying to build the project (Windows 10 / dotnetcore 2.2) I get the following error:

> ldap.net\ldap\Asn1\AsnXml.targets(19,5): error MSB4062: The "Microsoft.Build.Tasks.XslTransformation" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [ldap.net\ldap\ldap.csproj]

**Comment by panicbit** [comment]
This is confusing. It fails to build on both, Windows 10 and a WSL Arch installation, but it builds just fine on travis https://travis-ci.com/panicbit/ldap.net/jobs/164634723

**Comment by panicbit** [comment]
It looks like it actually builds fine everywhere except on Windows / WSL.
Also, after magically blessing the source with `msbuild`, the project somehow builds fine with dotnet tools, EVEN after `git clean -xfd`.
:confounded:

**Comment by zivillian** [comment]
Adding `/p:RunningOnCore=true` also solves the problem:
`dotnet build -c Release /p:RunningOnCore=true`
