### ISSUE TITLE
cyclic references

### ISSUE THREAD

**Issue by zivillian** [zivillian/ldap.net#2]
[RFC 4511 - 4.5.1](https://tools.ietf.org/html/rfc4511#section-4.5.1)

```
Filter ::= CHOICE {
...
             not             [2] Filter,
...
```

https://github.com/zivillian/ldap.net/blob/8389e4e6e091738074230875f557ef4b4e8cbc6e/ldap/Asn1/Asn1Filter.cs#L35-L38

I currently cannot change the type to
```csharp
public Asn1Filter Not;
```

I can't use a struct
> causes a cycle in struct layout

Trying to use a class results in

```
System.Security.Cryptography.Asn1.AsnSerializationConstraintException :
The tag (ContextSpecific 0) for field 'And' on type 'zivillian.ldap.Asn1.Asn1Filter'
already is associated in this context with field 'And' on type 'zivillian.ldap.Asn1.Asn1Filter'.
```

**Comment by zivillian** [comment]
I tried to use the XML generator, but it's generating a struct with cycles:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<asn:Choice
  xmlns:asn="http://schemas.dot.net/asnxml/201808/"
  name="Asn1Filter"
  namespace="zivillian.ldap.Asn1.Generated">
  <asn:SetOf name="And" implicitTag="0">
    <asn:AsnType typeName="Asn1Filter"/>
  </asn:SetOf>
  <asn:SetOf name="Or" implicitTag="1">
    <asn:AsnType typeName="Asn1Filter"/>
  </asn:SetOf>
  <asn:AsnType name="Not" typeName="Asn1Filter" implicitTag="2"/>
</asn:Choice>
```

```csharp
[StructLayout(LayoutKind.Sequential)]
internal partial struct Asn1Filter
{
    internal Asn1Filter[] And;
    internal Asn1Filter[] Or;
    internal Asn1Filter? Not;
...
}
```

**Comment by filipnavara** [comment]
I think this a valid concern. There is no longer a need to generate structures with the StructLayout attribute (which is there to suppress warnings/errors about uninitialized fields).

**Comment by zivillian** [comment]
I switched to classes and added the missing `Decode` method for cyclic choice fields in 7000bdf95aa9b4571f45eb3a215053d41348c8ea
