### ISSUE TITLE
Sequence of OCTET STRING

### ISSUE THREAD

**Issue by zivillian** [zivillian/ldap.net#3]
[RFC 4511 - 4.5.1](https://tools.ietf.org/html/rfc4511#section-4.5.1)

```
SearchRequest ::= [APPLICATION 3] SEQUENCE {
     baseObject      LDAPDN,
...
     attributes      AttributeSelection }

AttributeSelection ::= SEQUENCE OF selector LDAPString
                -- The LDAPString is constrained to
                -- <attributeSelector> in Section 4.5.1.8

LDAPString ::= OCTET STRING -- UTF-8 encoded,
                                    -- [ISO10646] characters
```

https://github.com/zivillian/ldap.net/blob/8389e4e6e091738074230875f557ef4b4e8cbc6e/ldap/Asn1/Asn1SearchRequest.cs#L42-L44

I can't combine `SequenceOf` and `OctetString`.

**Comment by zivillian** [comment]
May be a dupe of dotnet/corefx#28683

**Comment by filipnavara** [comment]
This should work just fine with the ASN code generator. That said, why doesn't `ReadOnlyMemory<byte>[]` with `SequenceOf` and `OctetString` (and `ExpectedTag`) work for you?

**Comment by zivillian** [comment]
It throws an Exception in https://github.com/zivillian/ldap.net/blob/e53bfccc81e647b10c17c36efde8d633a46f86ed/asn.1/Asn1V2.Serializer.cs#L1075-L1081
because both derive from `AsnTypeAttribute`.
https://github.com/zivillian/ldap.net/blob/e53bfccc81e647b10c17c36efde8d633a46f86ed/asn.1/Asn1V2.Serializer.cs#L1626
https://github.com/zivillian/ldap.net/blob/e53bfccc81e647b10c17c36efde8d633a46f86ed/asn.1/Asn1V2.Serializer.cs#L1578

**Comment by filipnavara** [comment]
It's possible to workaround that with a dummy `Choice` struct instead of using `OctetString` directly, but it's a bit of a hack.

Definitely recommend the code generator as an alternative here. The serializer is unlikely to get shipped as production ready anyway. In case the CoreFX guys decide to ship it then it should probably be addressed though.
